name: Test and Build

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
        job-type: [test, build]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
          node-version-file: ".nvmrc"
        
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Run tests
        if: matrix.job-type == 'test'
        run: yarn test
        
      - name: Build project
        if: matrix.job-type == 'build'
        run: yarn build
      